name: publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
          server-id: github

      - name: settings
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [
                {
                  "id": "compass", 
                  "username": "OliUmbi", 
                  "password": "${{ secrets.PAT }}"
                }
            ]

      - name: package
        run: mvn clean package

      - name: log in
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/unclet
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=${{ github.ref_name }}

          docker build . --tag $IMAGE_ID:latest --tag $IMAGE_ID:$VERSION
          docker push $IMAGE_ID --all-tags
